### ISSUE TITLE
Python 3.11 Wheel

### ISSUE THREAD

**Issue by kylestach** [google-deepmind/envlogger#7]
Would it be possible to get an updated Python 3.11 build of the `envlogger` wheels?

**Comment by kenjitoyama** [comment]
Hi! I'll try to take a look at this later this week. Cheers.

**Comment by kenjitoyama** [comment]
Hello @kylestach! I just pushed a new 1.2 release to PyPi with support for Python 3.11: https://pypi.org/project/envlogger/1.2/#files

I'll close this bug for now, but let me know if you encounter any problems.
